### ISSUE TITLE
Ability to manually specify experiment ID in `replicate.init`

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#177]
Two use cases:

1. Resuming an experiment: If a training node dies, you're in luck because you've used Replicate to save all your progress to the cloud. But there's currently no way to resume an experiment. The simplest way to enable resume would be to let the user set an experiment ID manually

2. AI Platform: When you launch an AI Platform training job you have to give it a job name. You probably want this linked to an experiment. You could do that right now using `params`, but it feels cleaner to have the AI Platform job ID also be the Replicate experiment ID

**Comment by bfirsh** [comment]
I've split this out into two roadmap tickets that describe the high-level features: #281 #283
