### ISSUE TITLE
Allow specifying storage_url in replicate.init()

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#178]
This is potentially controversial and I'm curious to hear your thoughts.

When using AI Platform, you launch jobs by pointing to the path of a Python package. AI Platform then packages that with sdist locally, uploads it to GCS, and executes a module in that package on the worker node.

This makes it really hard to use replicate.yaml, since we don't know which directory the training script is executed in, nor do we know the exact path to the installed package so we can't include replicate.yaml in the package and point to it with `--project-directory`.

The only alternative I can see is for us to add a `project_directory` argument to `replicate.init()`. But then we have two ways of specifying project directories, which may be confusing and hard to maintain. Still, my hunch is that AI Platform isn't the only case we'll run into this issue, so we should probably support that.

**Comment by bfirsh** [comment]
Fixed in #243
