### ISSUE TITLE
Fetching new data is slow

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#181]
It takes about 9 seconds to fetch new data in my current project:
```
$ (replicate ls --json | jq '.[].num_checkpoints') 2>&1 | ts
Oct 06 18:36:18 ═══╡ Fetching new data from "gs://andreas-bookrec-2"...
Oct 06 18:36:27 399
Oct 06 18:36:27 2952
Oct 06 18:36:27 332
Oct 06 18:36:27 27
```

Which means that almost everything I do with Replicate takes at least 9 seconds. It makes my whole process feel very sluggish.

In this project I have 4 experiments, with between 26 and 2952 checkpoints.

**Comment by bfirsh** [comment]
fixed in #192
