### ISSUE TITLE
`replicate ls` output is very wide

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#182]
![image](https://user-images.githubusercontent.com/713993/95268935-9f602080-0838-11eb-9260-138e1045828b.png)

Not sure what to do about it really, I am interested in all the data that is displayed (except maybe user and host since I'm doing this project alone). So maybe we can just close this ticket unless you have a clever idea @bfirsh?

**Comment by bfirsh** [comment]
Turned this into a roadmap ticket: #284
