### ISSUE TITLE
Speed up reading data in Python

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate#287]
# Why

When reading data from Python, it is currently reading metadata directly from storage instead of syncing like the CLI does. This is very inefficient.

# How

We should expose syncing metadata in the shared API, and have Python call it. We may need to implement the cached storage in Python, or perhaps that could be exposed in the shared API.

**Comment by andreasjansson** [comment]
Fixed by https://github.com/replicate/replicate/pull/408
