### ISSUE TITLE
Upload experiment/checkpoint data in the background

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate#317]
# Why

There is no reason we need to upload data synchronously, and it can sometimes take a while.

# How

Some ideas
- The Go shared library could become a forked daemon to handle upload jobs.
- When process quits, it waits for uploads to finish and shows progress.

# User data

At least 2 people have specifically asked for this.

**Comment by andreasjansson** [comment]
I'm picking this up by implementing https://github.com/replicate/replicate/issues/344
