### ISSUE TITLE
Filter name for creation time is called "started" instead of "created"

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#342]
This is confusing and error prone. It should be called "created" to be consistent with the rest of the CLI and Python API.

**Comment by karansangha** [comment]
@bfirsh can I take this one up?

**Comment by andreasjansson** [comment]
That would be fantastic, thank you @karansangha! It would be great if it were backwards-compatible with the current (broken) filter name, so that both `replicate ls --filter "created < 2020-11-20 15:00"` and `replicate ls --filter "started < 2020-11-20 15:00"` do the same thing, with the latter perhaps logging a deprecation warning to the console.

**Comment by murthy95** [comment]
@bfirsh @andreasjansson I have a working patch to fix this issue. Since I didnt see any update on this I took this up. Can I PR this ?

**Comment by andreasjansson** [comment]
@murthy95 that sounds great, PR away! :)

**Comment by andreasjansson** [comment]
Fixed in https://github.com/replicate/replicate/pull/489
