### ISSUE TITLE
Migrate shared library to long-running process that communicates via GRPC

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate#344]
# Problem

Currently, the Python -> Go interface spawns a new subprocess for each call to something in Go, and uses Go's built-in jsonrpc for simplicity.

This is not ideal because:

- Spawning new processes is inefficient
- jsonrpc doesn't support binary data
- jsonrpc doesn't support streaming data

# Solution

The Go interface should probably be long running and expose a GRPC API.

# See also

This would make for a neat implementation of #317, is a precursor to #331, and this process could also handle heartbeats instead of spawning a separate Python process.

**Comment by andreasjansson** [comment]
I'm picking this up as part of https://github.com/replicate/replicate/issues/317
