### ISSUE TITLE
Support .yml extension for replicate.yaml

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate#351]
We read the config `replicate.yaml`, but we should also support the filename `replicate.yml`, because it is a common alternative extension. It needs support in both Python and Go.

**Comment by kvthr** [comment]
Hi @bfirsh, can I take up this issue?

**Comment by VastoLorde95** [comment]
I think this can be closed now?

**Comment by andreasjansson** [comment]
Yes, thanks @VastoLorde95! Implemented in https://github.com/replicate/replicate/pull/386
