### ISSUE TITLE
Check out individual files

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate#358]
# Why

Currently, you can only check out the entire directory that you save. You should be able to check out individual files.

# Potential solution

```
replicate checkout abc123 -f model.pth
```

But what about checking out directories? Then `-f` is a bit weird.

# Design considerations

Some design thinking is needed about what path things are checked out as. If you do this on a checkpoint which has `data/model.pth`:

```
replicate checkout abc123 -o out/
```

It will create `out/data/model.pth`. If you do this:

```
replicate checkout abc123 -o out/ -f data/model.pth
```

Then you might expect it to appear as `out/model.pth`, but that would be inconsistent with behavior when you don't pass `-f`. Similarly, what about `-o out/somemodel.pth -f data/model.pth`?

**Comment by VastoLorde95** [comment]
Taking this up.

I feel we should focus on being consistent to the original interface and introducing some extra behavior for the sake of convenience.

I believe the -f flag is already used for "forced checkout". I wouldn't mind using "-file" instead.

I propose this -

### Case 1: Checking out a file without an output directory provided.

`replicate checkout abc123 -file data/model.pth`

Result: data/model.pth

### Case 2: Checking out a file with an output directory provided.

`replicate checkout abc123 -o out/ -file data/model.pth`

Result: out/data/model.pth

### Case 3: Checking out a file with an output filename provided.

`replicate checkout abc123 -o out/new_model.pth -file data/model.pth`

Result: out/new_model.pth

Saves the user from checking out a file and renaming it and is also a natural behavior that the user would expect.

**Comment by bfirsh** [comment]
Super! Thanks so much for picking this up. Good point on `-f` -- I forgot about that.

I wonder if `--path` might be a better name for the option? That way it'd also work with directories. For example: `replicate checkout abc123 -o out/ --path data/`
    
I think this might also fix the problem with the paths I mentioned.
  - `--file` option feels like you're "picking" a file and it'll show up in exactly the location you define, like copy. (`cp data/model.pth out/` produces `out/model.pth`)
  - `--path` feels more like you're "filtering" the output, like git checkout (`git --work-tree out/ checkout HEAD -- data/` produces `out/data/model.pth`).
    
The problem with both of these names is it's too generic. `--out` is a path too! We kinda want to call it `--in` but that doesn't make any sense. Maybe, riffing off the previous thinking, "filter" might be right word? That doesn't feel quite right either though.
    
Either way, maybe let's run with `--path` and we can always change it. This won't affect the implementation, I think.

BTW -- Even though we could use `-p`, I might suggest we start with `--path` and add the short option later if we have settled on it and it is widely used. Using the long option gives us the freedom to rename it without polluting the short flag namespace (see https://clig.dev/#arguments-and-flags ).

**Comment by VastoLorde95** [comment]
Agreed, --path sounds better. Working on it!

**Comment by bfirsh** [comment]
Thanks so much @VastoLorde95!
