### ISSUE TITLE
PyTorch Lightning integration

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#367]
Similar to our existing [Keras integration](https://replicate.ai/docs/guides/keras-integration), we should support PyTorch Lightning as a [custom logger](https://pytorch-lightning.readthedocs.io/en/latest/loggers.html).

**Comment by gan3sh500** [comment]
Can I take this up? I am a bit familiar with the PL loggers.

**Comment by bfirsh** [comment]
@gan3sh500 For sure! Feel free. :)

**Comment by gan3sh500** [comment]
@bfirsh @andreasjansson I've created a PR for this as a Callback as PL has a callback for ModelCheckpoint. Please have a look when you can, I have doubts on how to go forward with the PR.

**Comment by andreasjansson** [comment]
Implemented in https://github.com/replicate/replicate/pull/405

**Comment by bfirsh** [comment]
Thanks so much for your help with this @gan3sh500!
