### ISSUE TITLE
Cloud Storage Notebook link is broken

### ISSUE THREAD

**Issue by aaur0** [replicate/replicate#368]
https://colab.research.google.com/docs/guides/cloud-storage doesn't work

Steps to replicate
1. Go to https://colab.research.google.com/drive/1iypzEOysdACpIIXrM0RoGz9kg6z93XMP#scrollTo=Mgs9TbGd-8Fn
2. Click on "How to store experiment data in the cloud" in the What's next section

**Comment by bfirsh** [comment]
Ah -- thanks for that catch! I blindly copied and pasted the markdown from the website...
