### ISSUE TITLE
No module named 'replicate.keras_callback'

### ISSUE THREAD

**Issue by stvogel** [replicate/replicate#390]
I really like the concept of replicate and would like to integrate it with my keras-training. So I used the keras-integration-tutorial.
But:
```
from replicate.keras_callback import ReplicateCallback
```
just yields: `ModuleNotFoundError: No module named 'replicate.keras_callback'`
I'm using: 
`replicate==0.1.16`
... and as I'm writing this issue, I see that this seems to be the most recent version on windows.

But for linux there is already 0.2.1, which indeed has the ReplicateCallback.

So for everyone having this issue, switch to linux. ;-)
Or maybe a more recent replicate-version for windows could be pushed to pypi.

**Comment by bfirsh** [comment]
@stvogel As you've closed this, I think you may have discovered https://github.com/replicate/replicate/issues/280!

Unfortunately we don't have Windows support yet. Did you figure some other solution for this, out of interest?

**Comment by stvogel** [comment]
You are right ... Reading the docs, I saw that windows is currently not supported.
My solution was simply running Jupyter in WSL.
But I left my thumbs up on #280 as I think windows-support is really necessary as mostly all other relevant ML-tools needed for business are available on windows, too. (Pun against pytorch intended ;-))

**Comment by bfirsh** [comment]
@stvogel Ah, neat! So is replicate working for you running inside WSL?

I'm playing with windows support here to see how much work is involved: #426

**Comment by stvogel** [comment]
WSL was no problem, pip used the newest release and it worked right out of the box.
